# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCGTSCommunity Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR MCGTSCommunity"
welcomeDescription = "Notre mission est de recréer un monde autour du GTS !"
welcomeDescCTA = "Vous êtes à quelques clics de MCGTSCommunity."

