# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCGTSCommunity Launcher"

[ejs.landing]
mediaGitHubURL = "https://mcgtscommunity.websr.fr"
mediaXURL = "https://mcgtscommunity.websr.fr/"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/SgPDhb3vMX"

[ejs.settings]
sourceGithubLink = "https://github.com/yagourokogmod-netizen/MCCommunity"
supportLink = "https://discord.gg/SgPDhb3vMX"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR MCGTSCommunity"
welcomeDescription = "Notre mission est de recréer un monde autour du GTS !"
welcomeDescCTA = "Vous êtes à quelques clics de MCGTSCommunity."

